//! Semantic search over a corpus, end to end on CPU.
//!
//! ```text
//! # ad-hoc query against the bundled corpus
//! cargo run --release --example search -- .models/LFM2.5-Embedding-350M \
//!     --query "how do I stop two threads corrupting shared state"
//!
//! # score the whole labelled corpus
//! cargo run --release --example search -- .models/LFM2.5-Embedding-350M --eval
//!
//! # index a directory of your own text/code instead
//! cargo run --release --example search -- .models/LFM2.5-Embedding-350M \
//!     --dir src --query "where is the attention mask built"
//! ```
//!
//! The eval corpus is hand-authored (see `tests/data/README.md`) — it is
//! deliberately NOT generated by an embedding model, because scoring a
//! model against its own output measures nothing.

use std::time::Instant;

use candle_core::{DType, Device};
use lfm2_encoder::{cosine_similarity, Lfm2Embedding, TextKind};
use serde::Deserialize;

#[derive(Deserialize)]
struct Corpus {
    documents: Vec<Document>,
    queries: Vec<Query>,
}

#[derive(Deserialize)]
struct Document {
    id: String,
    text: String,
    topic: String,
}

#[derive(Deserialize)]
struct Query {
    id: String,
    text: String,
    relevant: Vec<String>,
    hard_negatives: Vec<String>,
}

/// An embedded corpus: normalized vectors, so cosine is a dot product.
struct Index {
    ids: Vec<String>,
    texts: Vec<String>,
    vectors: Vec<Vec<f32>>,
}

impl Index {
    fn build(model: &Lfm2Embedding, items: &[(String, String)]) -> lfm2_encoder::Result<Self> {
        let mut ids = Vec::with_capacity(items.len());
        let mut texts = Vec::with_capacity(items.len());
        let mut vectors = Vec::with_capacity(items.len());
        for (id, text) in items {
            // Corpus side always takes the DOCUMENT prefix.
            vectors.push(model.embed_normalized(text, TextKind::Document)?);
            ids.push(id.clone());
            texts.push(text.clone());
        }
        Ok(Self { ids, texts, vectors })
    }

    /// Top-k by cosine. Queries take the QUERY prefix — mixing the two up
    /// is the silent failure this model punishes.
    fn search(
        &self,
        model: &Lfm2Embedding,
        query: &str,
        k: usize,
    ) -> lfm2_encoder::Result<Vec<(f32, usize)>> {
        let q = model.embed_normalized(query, TextKind::Query)?;
        let mut scored: Vec<(f32, usize)> = self
            .vectors
            .iter()
            .enumerate()
            .map(|(i, v)| (cosine_similarity(&q, v), i))
            .collect();
        scored.sort_by(|a, b| b.0.total_cmp(&a.0));
        scored.truncate(k);
        Ok(scored)
    }
}

fn load_corpus() -> Corpus {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/data/semantic_search_eval.json");
    let bytes = std::fs::read(path).unwrap_or_else(|e| panic!("read {path}: {e}"));
    serde_json::from_slice(&bytes).expect("parse corpus")
}

/// Read a directory tree's text files as documents.
fn load_dir(root: &str) -> Vec<(String, String)> {
    fn walk(dir: &std::path::Path, out: &mut Vec<(String, String)>) {
        let Ok(entries) = std::fs::read_dir(dir) else {
            return;
        };
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                walk(&path, out);
            } else if let Ok(text) = std::fs::read_to_string(&path) {
                // One chunk per paragraph keeps chunks inside the 512-token
                // window and gives search something granular to return.
                for (n, chunk) in text.split("\n\n").enumerate() {
                    let chunk = chunk.trim();
                    if chunk.len() > 40 {
                        out.push((format!("{}#{n}", path.display()), chunk.to_string()));
                    }
                }
            }
        }
    }
    let mut out = Vec::new();
    walk(std::path::Path::new(root), &mut out);
    out
}

fn main() -> lfm2_encoder::Result<()> {
    let args: Vec<String> = std::env::args().skip(1).collect();
    let dir = args.first().cloned().unwrap_or_else(|| {
        eprintln!("usage: search <checkpoint-dir> [--eval] [--query TEXT] [--dir DIR] [--dtype f16]");
        std::process::exit(2);
    });
    let flag = |name: &str| args.iter().any(|a| a == name);
    let value = |name: &str| {
        args.iter()
            .position(|a| a == name)
            .and_then(|i| args.get(i + 1))
            .cloned()
    };

    let dtype = match value("--dtype").as_deref() {
        Some("f16") => DType::F16,
        _ => DType::F32,
    };

    let model = Lfm2Embedding::from_dir_with(&dir, dtype, &Device::Cpu)?;

    let items: Vec<(String, String)> = match value("--dir") {
        Some(d) => load_dir(&d),
        None => load_corpus()
            .documents
            .into_iter()
            .map(|d| (format!("{} [{}]", d.id, d.topic), d.text))
            .collect(),
    };

    let t = Instant::now();
    let index = Index::build(&model, &items)?;
    let elapsed = t.elapsed();
    println!(
        "indexed {} chunks in {:.2?} ({:.1?}/chunk, {dtype:?})\n",
        index.ids.len(),
        elapsed,
        elapsed / index.ids.len().max(1) as u32
    );

    if let Some(q) = value("--query") {
        let hits = index.search(&model, &q, 5)?;
        println!("query: {q}\n");
        for (score, i) in hits {
            let text: String = index.texts[i].chars().take(96).collect();
            println!("  {score:.4}  {}\n          {text}", index.ids[i]);
        }
    }

    if flag("--eval") {
        eval(&model, &index)?;
    }
    Ok(())
}

/// Recall@k plus the measure that actually separates a good retriever from
/// a lucky one: does the hard negative outrank the true positive?
fn eval(model: &Lfm2Embedding, index: &Index) -> lfm2_encoder::Result<()> {
    let corpus = load_corpus();
    let position = |id: &str| index.ids.iter().position(|s| s.starts_with(&format!("{id} ")));

    let (mut hit1, mut hit3, mut hit5) = (0usize, 0usize, 0usize);
    let mut neg_beats_pos = 0usize;
    let mut neg_checked = 0usize;
    let mut failures = Vec::new();

    let t = Instant::now();
    for q in &corpus.queries {
        let ranked = index.search(model, &q.text, index.ids.len())?;
        let rank_of = |id: &str| -> Option<usize> {
            let idx = position(id)?;
            ranked.iter().position(|(_, i)| *i == idx)
        };

        let best_relevant = q.relevant.iter().filter_map(|id| rank_of(id)).min();
        let Some(best) = best_relevant else { continue };
        if best == 0 {
            hit1 += 1;
        }
        if best < 3 {
            hit3 += 1;
        }
        if best < 5 {
            hit5 += 1;
        } else {
            failures.push((q.id.clone(), q.text.clone(), best));
        }

        for neg in &q.hard_negatives {
            if let Some(nr) = rank_of(neg) {
                neg_checked += 1;
                if nr < best {
                    neg_beats_pos += 1;
                }
            }
        }
    }

    let n = corpus.queries.len() as f64;
    println!("\n─── retrieval over {} docs, {} queries ({:.2?})", index.ids.len(), corpus.queries.len(), t.elapsed());
    println!("  recall@1  {:.1}%", 100.0 * hit1 as f64 / n);
    println!("  recall@3  {:.1}%", 100.0 * hit3 as f64 / n);
    println!("  recall@5  {:.1}%", 100.0 * hit5 as f64 / n);
    println!(
        "  hard negative outranks best relevant: {neg_beats_pos}/{neg_checked} ({:.1}%)",
        100.0 * neg_beats_pos as f64 / neg_checked.max(1) as f64
    );
    if !failures.is_empty() {
        println!("\n  missed at k=5:");
        for (id, text, rank) in failures.iter().take(6) {
            println!("    {id} (best relevant at rank {rank}): {text}");
        }
    }
    Ok(())
}
